apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubdemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubdemoapp
  template:
    metadata:
      labels:
        app: kubdemoapp
    spec:
      containers:
        - name: kubdemoapp
          image: sparshitha/game:kubeimage1
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
